### ISSUE TITLE
Failing tests with python 3.8, 3.9

### ISSUE THREAD

**Issue by nileshpatra** [python-streamz/streamz#372]
I maintain this as a package in Debian
Several logs similar to this:
Complete log is availaible [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973178)

```
> platform linux -- Python 3.9.0+, pytest-4.6.11, py-1.9.0, pluggy-0.13.0
> rootdir: /<<PKGBUILDDIR>>
> plugins: flaky-3.7.0
> collected 1518 items / 2 skipped / 1516 selected
> 
> streamz/dataframe/tests/test_dataframe_utils.py .s.s                     [  0%]
> streamz/dataframe/tests/test_dataframes.py ............................. [  2%]
> ........................................................................ [  6%]
> ........................................................................ [ 11%]
> .......................................................................s [ 16%]
> ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 21%]
> ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 25%]
> ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 30%]
> ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 35%]
> ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 40%]
> sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss. [ 44%]
> ...xxxxxx....................ss......................................... [ 49%]
> ....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X. [ 54%]
> ....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X. [ 59%]
> ....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X. [ 63%]
> ....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X.....X. [ 68%]
> .....X......X......X......X......X......X......X......X......X......X... [ 73%]
> ...X......X......X......X......X......X......X......X......X......X..... [ 78%]
> .X......X......X......X......X......X......X......X......X......X......X [ 82%]
> ......X......X......X......X......X......X......X......X......X......X.. [ 87%]
> ....X......X......X......X......X......X......X...............x..        [ 91%]
> streamz/tests/test_batch.py ....                                         [ 92%]
> streamz/tests/test_core.py ............................................. [ 95%]
> ...........................................................              [ 98%]
> streamz/tests/test_dask.py ssssFFFFFFsF                                  [ 99%]
> streamz/tests/test_sources.py XXXx                                       [100%]x [100%]x [100%]
> 
> =================================== FAILURES ===================================
> ___________________________________ test_map ___________________________________
> 
>     def test_func():
>         result = None
>         workers = []
>         with clean(timeout=active_rpc_timeout, **clean_kwargs) as loop:
>     
>             async def coro():
>                 with dask.config.set(config):
>                     s = False
>                     for i in range(5):
>                         try:
>                             s, ws = await start_cluster(
>                                 nthreads,
>                                 scheduler,
>                                 loop,
>                                 security=security,
>                                 Worker=Worker,
>                                 scheduler_kwargs=scheduler_kwargs,
>                                 worker_kwargs=worker_kwargs,
>                             )
>                         except Exception as e:
>                             logger.error(
>                                 "Failed to start gen_cluster, retrying",
>                                 exc_info=True,
>                             )
>                         else:
>                             workers[:] = ws
>                             args = [s] + workers
>                             break
>                     if s is False:
>                         raise Exception("Could not start cluster")
>                     if client:
>                         c = await Client(
>                             s.address,
>                             loop=loop,
>                             security=security,
>                             asynchronous=True,
>                             **client_kwargs
>                         )
>                         args = [c] + args
>                     try:
>                         future = func(*args)
>                         if timeout:
>                             future = asyncio.wait_for(future, timeout)
>                         result = await future
>                         if s.validate:
>                             s.validate_state()
>                     finally:
>                         if client and c.status not in ("closing", "closed"):
>                             await c._close(fast=s.status == "closed")
>                         await end_cluster(s, workers)
>                         await asyncio.wait_for(cleanup_global_workers(), 1)
>     
>                     try:
>                         c = await default_client()
>                     except ValueError:
>                         pass
>                     else:
>                         await c._close(fast=True)
>     
>                     for i in range(5):
>                         if all(c.closed() for c in Comm._instances):
>                             break
>                         else:
>                             await asyncio.sleep(0.05)
>                     else:
>                         L = [c for c in Comm._instances if not c.closed()]
>                         Comm._instances.clear()
>                         # raise ValueError("Unclosed Comms", L)
>                         print("Unclosed Comms", L)
>     
>                     return result
>     
> >           result = loop.run_sync(
>                 coro, timeout=timeout * 2 if timeout else timeout
>             )
> 
> /usr/lib/python3/dist-packages/distributed/utils_test.py:956: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> /usr/lib/python3/dist-packages/tornado/ioloop.py:532: in run_sync
>     return future_cell[0].result()
> /usr/lib/python3/dist-packages/distributed/utils_test.py:927: in coro
>     result = await future
> /usr/lib/python3.9/asyncio/tasks.py:476: in wait_for
>     return fut.result()
> /usr/lib/python3/dist-packages/tornado/gen.py:742: in run
>     yielded = self.gen.throw(*exc_info)  # type: ignore
> streamz/tests/test_dask.py:25: in test_map
>     yield source.emit(i)
> /usr/lib/python3/dist-packages/tornado/gen.py:735: in run
>     value = future.result()
> /usr/lib/python3/dist-packages/tornado/gen.py:501: in callback
>     result_list.append(f.result())
> /usr/lib/python3/dist-packages/tornado/gen.py:742: in run
>     yielded = self.gen.throw(*exc_info)  # type: ignore
> streamz/dask.py:113: in update
>     future_as_dict = yield client.scatter({tokenized_x: x}, asynchronous=True)
> /usr/lib/python3/dist-packages/tornado/gen.py:735: in run
>     value = future.result()
> /usr/lib/python3/dist-packages/distributed/client.py:1965: in _scatter
>     _, who_has, nbytes = await scatter_to_workers(
> /usr/lib/python3/dist-packages/distributed/utils_comm.py:144: in scatter_to_workers
>     out = await All(
> /usr/lib/python3/dist-packages/distributed/utils.py:235: in All
>     result = await tasks.next()
> /usr/lib/python3/dist-packages/distributed/core.py:757: in send_recv_from_rpc
>     result = await send_recv(comm=comm, op=key, **kwargs)
> /usr/lib/python3/dist-packages/distributed/core.py:540: in send_recv
>     response = await comm.read(deserializers=deserializers)
> /usr/lib/python3/dist-packages/distributed/comm/tcp.py:211: in read
>     msg = await from_frames(
> /usr/lib/python3/dist-packages/distributed/comm/utils.py:69: in from_frames
>     res = _from_frames()
> /usr/lib/python3/dist-packages/distributed/comm/utils.py:54: in _from_frames
>     return protocol.loads(
> /usr/lib/python3/dist-packages/distributed/protocol/core.py:106: in loads
>     header = msgpack.loads(header, use_list=False, **msgpack_opts)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> >   ???
> E   ValueError: tuple is not allowed for map key
> 
> msgpack/_unpacker.pyx:195: ValueError
> ----------------------------- Captured stderr call -----------------------------
> distributed.protocol.core - CRITICAL - Failed to deserialize
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/distributed/protocol/core.py", line 106, in loads
>     header = msgpack.loads(header, use_list=False, **msgpack_opts)
>   File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
> ValueError: tuple is not allowed for map key
> distributed.core - ERROR - tuple is not allowed for map key
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/distributed/core.py", line 346, in handle_comm
>     msg = await comm.read()
>   File "/usr/lib/python3/dist-packages/distributed/comm/tcp.py", line 211, in read
>     msg = await from_frames(
>   File "/usr/lib/python3/dist-packages/distributed/comm/utils.py", line 69, in from_frames
>     res = _from_frames()
>   File "/usr/lib/python3/dist-packages/distributed/comm/utils.py", line 54, in _from_frames
>     return protocol.loads(
>   File "/usr/lib/python3/dist-packages/distributed/protocol/core.py", line 106, in loads
>     header = msgpack.loads(header, use_list=False, **msgpack_opts)
>   File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
> ValueError: tuple is not allowed for map key
> distributed.protocol.core - CRITICAL - Failed to deserialize
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/distributed/protocol/core.py", line 106, in loads
>     header = msgpack.loads(header, use_list=False, **msgpack_opts)
>   File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
> ValueError: tuple is not allowed for map key
```

It'd be great to have this fixed!

**Comment by martindurant** [comment]
Are dask/distributed tests otherwise passing? The message suggests a change in msgpack (i.e., not strictly connected with this project). Can you provide your runtime versions, please?

**Comment by nileshpatra** [comment]
Thanks @martindurant for helping!

> Are dask/distributed tests otherwise passing? The message suggests a change in msgpack (i.e., not strictly connected with this project). Can you provide your runtime versions, please?

Yes, I suspect that's probably what broke this. It'd be nice if you could adapt to this change.
(Relevant)Versions:
```
python: 3.8, 3.9
msgpack: 1.0.0
tornado: 6.0.4
toolz: 0.9.0
pandas: 1.1.3
dask: 2.11.0
distributed: 2.10.0
zict: 2.0.0
six: 1.15.0
```

**Comment by nileshpatra** [comment]
Well, on further inspection, maybe msgpack ended up breaking distributed instead - but I'd want to seek your confirmation - that this has nothing to do with streamz?

**Comment by martindurant** [comment]
Streamz has only evolved slowly, and has been passing its own CI. I ran py38 locally without issue. Note that the msgpack version is almost brand new, but the version of distributed is over 8months old, so that mismatch might be the culprit.

**Comment by nileshpatra** [comment]
Yep, I suspected this too - need to fix distributed there. Thanks for the help and many thanks for maintaining streamz! :-)
