### ISSUE TITLE
Clean up Issues ?

### ISSUE THREAD

**Issue by quasiben** [python-streamz/streamz#385]
When running through some of the unit tests I see Exceptions which seem like clean up issues. 
For exmaple, when running:
> py.test -s -v test_dataframes.py::test_setitem

I see 
> Exception ignored in: <function Future.__del__ at 0x7fb7f59825e0>
Traceback (most recent call last):
  File "/datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/distributed/client.py", line 385, in __del__
  File "/datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/distributed/client.py", line 360, in release
  File "/datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 222, in add_callback
AttributeError: 'NoneType' object has no attribute 'get_ident'

The tests pass but I'm wondering if this a a known issue:

```
rootdir: /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests
plugins: asyncio-0.14.0
collected 2 items

test_dataframes.py::test_setitem[core] PASSED
test_dataframes.py::test_setitem[dask] PASSED

=============================================================================================================================== warnings summary ===============================================================================================================================
test_dataframes.py:384
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:384: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.slow

test_dataframes.py:388
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:388: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param({}, 'min', marks=pytest.mark.slow),

test_dataframes.py:390
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:390: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param({}, 'max', marks=pytest.mark.slow),

test_dataframes.py:391
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:391: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param({}, 'var', marks=pytest.mark.slow),

test_dataframes.py:392
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:392: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param({}, 'count', marks=pytest.mark.slow),

test_dataframes.py:394
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:394: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param({'quantile': 0.5}, 'quantile', marks=pytest.mark.slow)

test_dataframes.py:398
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:398: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param(2, marks=pytest.mark.slow),

test_dataframes.py:400
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:400: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param('3h', marks=pytest.mark.slow),

test_dataframes.py:405
  /datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/streamz/dataframe/tests/test_dataframes.py:405: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytest.param(5, marks=pytest.mark.slow)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================================================== 2 passed, 9 warnings in 3.75s =========================================================================================================================
Exception ignored in: <function Future.__del__ at 0x7fb7f59825e0>
Traceback (most recent call last):
  File "/datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/distributed/client.py", line 385, in __del__
  File "/datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/distributed/client.py", line 360, in release
  File "/datasets/bzaitlen/miniconda3/envs/2020112/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 222, in add_callback
AttributeError: 'NoneType' object has no attribute 'get_ident'
```

cc @kkraus14

**Comment by martindurant** [comment]
I wonder if we can trigger this with distributed alone? We generally want to use weakref.finalize rather than `__del__` for cleanup, since it's possible that modules and variables have been unloaded at cleanup time, if this happens during interpreter shutdown.

**Comment by quasiben** [comment]
It's not necessarily a stream issue.  I was able to reproduce with just distributed:


```python
import dask.array as da
import numpy
from distributed import Client, wait
if __name__ == "__main__":
    client = Client(n_workers=2)
    a = numpy.arange(1500 * 1500).reshape((1500, 1500)).astype(numpy.float32)
    a = da.from_array(a).persist()
    a = a.rechunk((500, 500))
    print(a)
    b = a.persist()
    wait((b.dot(b.T)).persist())
    print('finished')
```

**Comment by martindurant** [comment]
Actually, that doesn't cause any problem for me :)
The del method looks like
```python
    def __del__(self):
        try:
            self.release()
        except RuntimeError:  # closed event loop
            pass
```
so I suppose it can catch the `AttributeError` too, or otherwise have a way to discern that we are in shutdown. I assume that if the "client-releases-keys" message is never sent to the scheduler, the keys are eventually released anyway, when the scheduler realises that client has gone.

This should be moved to dask/distributed I think.

**Comment by martindurant** [comment]
To add to the thread, I see:
```
    def _inc_ref(self, key):
        with self._refcount_lock:
            self.refcount[key] += 1

    def _dec_ref(self, key):
        with self._refcount_lock:
            self.refcount[key] -= 1
            if self.refcount[key] == 0:
                del self.refcount[key]
                self._release_key(key)
```
(distributed.client.Client)
and I am a little surprised by the use of a lock, since `+=` and `-=` are atomic in python due to the GIL, at least until maybe the code is cythonised. Then again, acquiring a lock should take negligible time when the client is normally running single-threaded.

**Comment by quasiben** [comment]
Thank you for looking at this with me @martindurant .  It appears that I can only reproduce this on a DGX machine.  On my local laptop (Macbook) I don't see this issue.  

Agreed we should move to dask/distributed

**Comment by martindurant** [comment]
Hm, I only seem to be able to transfer to a repo in the same org (and there aren't any!)

**Comment by quasiben** [comment]
Moved to distributed.  Closing.  Thanks @martindurant !
