### ISSUE TITLE
Error: dask w/ non-pure function

### ISSUE THREAD

**Issue by wwoods** [python-streamz/streamz#394]
Expected: below program works fine, prints 1000 random numbers

```python
import dask.distributed
import random
import streamz

if __name__ == '__main__':
    with dask.distributed.Client() as client:
        s = streamz.Stream()
        ss = s
        ss = ss.scatter()
        # This function is not pure, so to avoid dask's caching mechanism, we
        # should need to pass `pure=False`. Interestingly, the crash happens
        # either way.
        ss = ss.map(lambda x: random.random(), pure=False)
        ss = ss.gather()
        ss = ss.sink(print)

        for _ in range(1000):
            s.emit('d')
```

Actual:

```
$ python dask_streamz_crash.py
0.9399631240012536
Traceback (most recent call last):
  File "dask_streamz_crash.py", line 15, in <module>
    s.emit('d')
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/core.py", line 449, in emit
    sync(self.loop, _)
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/core.py", line 1746, in sync
    six.reraise(*error[0])
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/core.py", line 1731, in f
    result[0] = yield future
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/core.py", line 444, in _
    result = yield self._emit(x, metadata=metadata)
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 526, in callback
    result_list.append(f.result())
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/dask.py", line 115, in update
    f = yield self._emit(future, metadata=metadata)
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 526, in callback
    result_list.append(f.result())
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/dask.py", line 144, in update
    result = yield client.gather(x, asynchronous=True)
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/distributed/client.py", line 1852, in _gather
    raise exc
concurrent.futures._base.CancelledError: lambda-5459ebc7b2c52892a83cbc2f5cff86ad
```

Versions: python==3.8.5, dask==2.30.0, streamz==0.6.1

**Comment by wwoods** [comment]
Minor update: the `pure=True` version may be fixed, with incorrect results, by waiting on `RefCounter`s at the end:

```python
        refs = []
        for _ in range(1000):
            rc = streamz.RefCounter()
            s.emit('d', metadata=[{'ref': rc}])
            refs.append(rc)
        while max([r.count for r in refs]) != 0:
            time.sleep(.1)
```

However, this does not help the `pure=False` version.

**Comment by martindurant** [comment]
I don't think `map` supports `pure=False` (this is not the same as `client.map`).
The actual error looks a lot like #397

**Comment by wwoods** [comment]
The code base forwards additional kwargs to `streamz.map` to `client.map` (https://github.com/python-streamz/streamz/blob/master/streamz/dask.py#L58), so my assumption would be that it should work. The solution to the two issues is possibly the same.
